version: '3'
services:
  postgresdb:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/user-behavior-analysis
    restart: always 
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
    driver: local